config/routes.rb
Rails.application.routes.draw do

  resources :players
  resources :fixtures
  resources :tables
  resources :leagues

  root "home#index"
  get 'home/index'
  get 'home/about'
  get '/search', to: 'tables#search'


end

app/models/league.rb
class League < ApplicationRecord
  validates :league_name, presence: true
  has_many :tables
  has_many :fixtures
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: %i[ show edit update destroy ]

  # GET /leagues or /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1 or /leagues/1.json
  def show
    @league = League.find(params[:id])
    @tables = @league.tables
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues or /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to league_url(@league), notice: "League was successfully created." }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1 or /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to league_url(@league), notice: "League was successfully updated." }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1 or /leagues/1.json
  def destroy
    @league.destroy

    respond_to do |format|
      format.html { redirect_to leagues_url, notice: "League was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def league_params
      params.require(:league).permit(:league_name)
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_with(model: league) do |form| %>
  <% if league.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
        <% league.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :league_name, style: "display: block" %>
    <%= form.text_field :league_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/leagues/_league.html.erb
<div id="<%= dom_id league %>">
  <p>
    <strong>League name:</strong>
    <%= league.league_name %>
  </p>

</div>

app/views/leagues/edit.html.erb
<h1>Editing league</h1>

<%= render "form", league: @league %>

<br>

<div>
  <%= link_to "Show this league", @league %> |
  <%= link_to "Back to leagues", leagues_path %>
</div>

app/views/leagues/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
<h1 class="mx-auto">Leagues</h1>

<div id="leagues" class="container border">
  <% @leagues.each do |league| %>
    <div class="container border">
      <h2><%= link_to league.league_name, league_path(league) %></h2>
    </div>
  <% end %>

</div>

<%= link_to "New league", new_league_path %>
</div>

app/views/leagues/new.html.erb
<h1>New league</h1>

<%= render "form", league: @league %>

<br>

<div>
  <%= link_to "Back to leagues", leagues_path %>
</div>

app/views/leagues/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container ">
<h1><%= @league.league_name %> </h1>

<h2>Teams:</h2>
<div class="container border bg-secondary m-3 p-3">
<% if @tables.any? %>
  <ul>
    <% @tables.each do |table| %>
      <li><h3 class="text-warning"><%= link_to table.name, table_path(table), class:"text-warning link-underline-opacity-0" %></h3></li>
    <% end %>
  </ul>
<% else %>
  <p>No tables found for this league.</p>
<% end %>
</div>

</div>