config/routes.rb
Rails.application.routes.draw do

  resources :players
  resources :fixtures
  resources :tables
  resources :leagues

  root "home#index"
  get 'home/index'
  get 'home/about'
  get '/search', to: 'tables#search'


end

app/models/fixture.rb
class Fixture < ApplicationRecord
  belongs_to :league
  belongs_to :table
end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController
  before_action :set_fixture, only: %i[ show edit update destroy ]

  # GET /fixtures or /fixtures.json
  def index
    @fixtures = Fixture.all
  end

  # GET /fixtures/1 or /fixtures/1.json
  def show
  end

  # GET /fixtures/new
  def new
    @fixture = Fixture.new
  end

  # GET /fixtures/1/edit
  def edit
  end

  # POST /fixtures or /fixtures.json
  def create
    @fixture = Fixture.new(fixture_params)

    respond_to do |format|
      if @fixture.save
        format.html { redirect_to fixture_url(@fixture), notice: "Fixture was successfully created." }
        format.json { render :show, status: :created, location: @fixture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fixture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fixtures/1 or /fixtures/1.json
  def update
    respond_to do |format|
      if @fixture.update(fixture_params)
        format.html { redirect_to fixture_url(@fixture), notice: "Fixture was successfully updated." }
        format.json { render :show, status: :ok, location: @fixture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fixture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fixtures/1 or /fixtures/1.json
  def destroy
    @fixture.destroy

    respond_to do |format|
      format.html { redirect_to fixtures_url, notice: "Fixture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fixture
      @fixture = Fixture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fixture_params
      params.require(:fixture).permit(:match_date, :match_time, :table_id, :league_id, :opponent)
    end
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/views/fixtures/_fixture.html.erb
<div id="<%= dom_id fixture %>">
  <p>
    <strong>Match date:</strong>
    <%= fixture.match_date %>
  </p>

  <p>
    <strong>Match time:</strong>
    <%= fixture.match_time %>
  </p>

  <p>
    <strong>Table:</strong>
    <%= fixture.table_id %>
  </p>

  <p>
    <strong>League:</strong>
    <%= fixture.league_id %>
  </p>

  <p>
    <strong>Opponent:</strong>
    <%= fixture.opponent %>
  </p>

</div>

app/views/fixtures/_form.html.erb
<%= form_with(model: fixture) do |form| %>
  <% if fixture.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fixture.errors.count, "error") %> prohibited this fixture from being saved:</h2>

      <ul>
        <% fixture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :match_date, style: "display: block" %>
    <%= form.date_field :match_date %>
  </div>

  <div>
    <%= form.label :match_time, style: "display: block" %>
    <%= form.time_field :match_time %>
  </div>

  <div>
    <%= form.label :table_id, style: "display: block" %>
    <%= form.number_field :table_id %>
  </div>

  <div>
    <%= form.label :league_id, style: "display: block" %>
    <%= form.number_field :league_id %>
  </div>

  <div>
    <%= form.label :opponent, style: "display: block" %>
    <%= form.text_field :opponent %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/fixtures/edit.html.erb
<h1>Editing fixture</h1>

<%= render "form", fixture: @fixture %>

<br>

<div>
  <%= link_to "Show this fixture", @fixture %> |
  <%= link_to "Back to fixtures", fixtures_path %>
</div>

app/views/fixtures/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Fixtures</h1>

<div id="fixtures">
  <% @fixtures.each do |fixture| %>
    <%= render fixture %>
    <p>
      <%= link_to "Show this fixture", fixture %>
    </p>
  <% end %>
</div>

<%= link_to "New fixture", new_fixture_path %>

app/views/fixtures/new.html.erb
<h1>New fixture</h1>

<%= render "form", fixture: @fixture %>

<br>

<div>
  <%= link_to "Back to fixtures", fixtures_path %>
</div>

app/views/fixtures/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @fixture %>

<div>
  <%= link_to "Edit this fixture", edit_fixture_path(@fixture) %> |
  <%= link_to "Back to fixtures", fixtures_path %>

  <%= button_to "Destroy this fixture", @fixture, method: :delete %>
</div>