config/routes.rb
Rails.application.routes.draw do

  resources :players
  resources :fixtures
  resources :tables
  resources :leagues

  root "home#index"
  get 'home/index'
  get 'home/about'
  get '/search', to: 'tables#search'


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about

  end

  def search

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav id="nav" class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">FootBall</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% if request.path != root_path %>
        <li class="nav-item">
          <%= link_to 'Home', root_path , class:'nav-link'%>
        </li>
        <%end%>
        <li class="nav-item">
          <%= link_to 'Leagues', leagues_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Teams', tables_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Players', players_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class:'nav-link' %>
        </li>
      </ul>
      <%= form_tag tables_path,class: "d-flex", method: :get do %>
        <%= text_field_tag :q, params[:q], placeholder: 'Search Teams', class: "form-control me-2" %>
        <%= submit_tag 'Search', class: "btn btn-outline-success" %>
      <% end %>

    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About</h1>
<p>The Api used for this project  is <a href="https://rapidapi.com/api-sports/api/api-football">Link</a>   .
It is an API that is based on football(soccer) information, that is the required data for this project.
In this Api, data is well structured in an understandable JSON format with various end points that makes it easier to fetch data and is inter-connected with ids.
For this project we will need 3 different tables named: leagues, tables, and players which are further elaborated in the ERD diagram.
</p>
<p>
We have used 3 different endpoints from the API above that provide us data about the different leagues, different teams and the different players
All the data fetched has unique id which makes it possible to relate and combine</p>
<p>Data source 1 fetches the leagues alog with the league_id from the api</p>
<p>Data Source 2 fetches the team information and is related to the leagues by league_id FK</p>
<p>Data Source 3 fetches the player data and is related by table_id FK</p>
<%= image_tag 'erd.png' , alt: "image" %>

app/views/home/index.html.erb
<div class="container">
<h1>FootBall</h1>

<div class="container border border-success">
<%= form_tag(search_path, method: :get) do %>
  <h3>Display a list of teams from a selected League</h3>
  <div class="form-group">
    <%= label_tag :league_id, 'Select League' %>
    <%= select_tag :league_id, options_for_select(League.all.map { |l| [l.league_name, l.id] }), include_blank: true, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= label_tag :table_name, 'Table Name' %>
    <%= text_field_tag :table_name, params[:table_name], class: 'form-control' %>
  </div>
  <%= submit_tag 'Search', class: 'btn btn-primary' %>
<% end %>
</div>

</div>