config/routes.rb
Rails.application.routes.draw do

  resources :players
  resources :fixtures
  resources :tables
  resources :leagues

  root "home#index"
  get 'home/index'
  get 'home/about'
  get '/search', to: 'tables#search'


end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: %i[ show edit update destroy ]
  before_action :search, only: [:index]

  #method for searching
  def search
    @tables = Table.includes(:league)
    @tables = @tables.where(league_id: params[:league_id]) if params[:league_id].present?
    @tables = @tables.where('name LIKE ?', "%#{params[:table_name]}%") if params[:table_name].present?
  end


  # GET /tables or /tables.json
  def index

    @tables = if params[:q]
        @tables = Table.where("name LIKE ?", "%#{params[:q]}%" )
      else
        Table.all
      end
  end

  # GET /tables/1 or /tables/1.json
  def show
    @table = Table.find(params[:id])
    @players = @table.players
    @league = League.find_by(id: @table.league_id)
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables or /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to table_url(@table), notice: "Table was successfully created." }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1 or /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to table_url(@table), notice: "Table was successfully updated." }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1 or /tables/1.json
  def destroy
    @table.destroy

    respond_to do |format|
      format.html { redirect_to tables_url, notice: "Table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def table_params
      params.require(:table).permit(:name, :points, :logo, :league_id)
    end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.erb
<%= form_with(model: table) do |form| %>
  <% if table.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
        <% table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>


  <div>
    <%= form.label :logo, style: "display: block" %>
    <%= form.text_field :logo %>
  </div>

  <div>
    <%= form.label :league_id, style: "display: block" %>
    <%= form.number_field :league_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tables/_table.html.erb
<div id="<%= dom_id table %>">
  <p>
    <strong>Name:</strong>
    <%= table.name %>
  </p>

  <p>
    <strong>Founded in:</strong>
    <%= table.founded %>
  </p>


  <p>
    <strong>Logo:</strong>
    <img src="<%= table.logo  %>" alt="logo">
  </p>

  <p>
    <strong>League:</strong>
    <%= table.league_id %>
  </p>

</div>

app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render "form", table: @table %>

<br>

<div>
  <%= link_to "Show this table", @table %> |
  <%= link_to "Back to tables", tables_path %>
</div>

app/views/tables/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
<h1>Tables</h1>

  <div id="tables" class="container border">
    <% @tables.each do |table| %>
    <div class="container border">
      <%= render table %>
      <p>
        <%= link_to "Show this table", table %>
      </p>
      </div>
    <% end %>

    x
  </div>

<%= link_to "New table", new_table_path %>
</div>

app/views/tables/new.html.erb
<h1>New table</h1>

<%= render "form", table: @table %>

<br>

<div>
  <%= link_to "Back to tables", tables_path %>
</div>

app/views/tables/search.html.erb
<h1>Search</h1>
<br>
<div class="container">
<ol>
<% @tables.each do |table| %>
  <li>
    <h3 class="text-warning"><%= link_to table.name, table_path(table), class:"text-warning link-underline-opacity-0" %></h3>
  </li>
<% end %>
</ol>
</div>

app/views/tables/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container ">
  <%= render @table %>
  <% if @league %>
    <h2><%= link_to @league.league_name, @league %></h2>
  <% end %>


  <div>

    <%= link_to "Back to tables", tables_path %>
  </div>

  <div class="container border bg-secondary m-3 p-3">
  <% if @players.any? %>
    <ul>
      <% @players.each do |player| %>
        <li><h3 ><%= link_to player.name, player_path(player) ,class: "text-dark"%></h3></li>
      <% end %>
    </ul>
  <% else %>
    <p>No Player found for this Team.</p>
  <% end %>
  </div>